---
name: Publish image

on:
  push:
    paths: 
      - "docker/**"
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get the latest tag
      id: latest_tag
      run: |
        export VERSION=$(awk '/appVersion:/ {print $2}' Chart.yaml | tr -d '"')
        echo "appVersion: ${VERSION}"
        echo ::set-output name=value::"${VERSION//v}"

    outputs:
      version: ${{ steps.latest_tag.outputs.value }}

  publish-image:
    runs-on: ubuntu-latest
    needs:
      - version

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      working-directory: ./docker/nfs-server
      run: |
        docker buildx build . --platform linux/amd64,linux/arm64,linux/arm/v7 --tag ghcr.io/two-tauers/nfs-server:${{ needs.version.outputs.version }} --tag ghcr.io/two-tauers/nfs-server:latest --push
